# Site settings
title: "Andrew Jackson"
description: "Andrew Jackson, Network Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Andrew Jackson"
resume_title:                   "Network Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "andyjax@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "847-513-3604"
resume_contact_address:         "2309 Central Street #3, Evanston, IL 60201"

resume_header_contact_info:     "2309 Central Street #3, Evanston, IL 60201 • 847-513-3604 • andyjax@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Andy is a Network Engineering professional with over 10 years experience working with various networking technologies including Firewall, Load Balancing, Switching, Routing and Wireless. He also has extensive experience developing network automation scripting in Python and Powershell. More recently, Andy has stepped into a Systems Engineering role, and is developing CI/CD pipelines with Travis-CI and Argo to deploy Kubernetes clusters into the cloud. Andy is looking to help organizations solve cloud-native problems with deep knowledge of Networking and Security while also having programming ability to deliver pipelines.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/andyjax"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/andyjax"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://resume.andyjax.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
